version: '3.8'

services:
  mongodb:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongodata:/data/db
    ports:
      - '27017:27017'

  backend:
    build: ./backend
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/trackmygroceries
      - PORT=4000
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/usr/src/app
    image: node:18-alpine
    working_dir: /usr/src/app
    command: ["node", "src/server.js"]

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/usr/src/app

volumes:
  mongodata: